Friends In High Places
townteki/townsquare pull request #354
Opened 2021-03-31 14:30 UTC by AaronSchnabel

This PR is so that the changes to callouts can be made so a dude can refuse a callout without going home booted.

2021-03-31 15:21 UTC, mmeldo commented
This one is not yet done ... adding effect for the callout refuse.

2021-04-01 08:19 UTC, mmeldo commented
@AaronSchnabel  Still needs the second ability to be implemented

2021-04-03 12:42 UTC, mmeldo requested changes

2021-04-03 12:42 UTC, mmeldo commented on server/game/cards/11-TCaR/FriendsInHighPlaces.js
> +                    waitingTitlePrompt: 'Waiting for opponent to select a dude',
```suggestion
                    activePromptTitle: 'Select a dude to make a stud',
                    waitingPromptTitle: 'Waiting for opponent to select a dude',
```
Typo in prompt property names.

2021-04-03 12:42 UTC, mmeldo commented on server/game/cards/11-TCaR/FriendsInHighPlaces.js
> +        return playerPosseDudes.map(dude => dude.influence).reduce((memo, influence) => memo + influence, 0);
I know I suggested this, but I found there is better and more effective way with just reduce. I am a freak when it comes to making code the most effective 😄 
```suggestion
        return playerPosseDudes.reduce((memo, dude) => memo + dude.influence, 0);
```

2021-04-03 17:22 UTC, merged

2021-04-04 13:46 UTC, tybar commented on server/game/cards/11-TCaR/FriendsInHighPlaces.js
> +                        condition: card => card.isParticipating() && card.isDraw()},
I'm not 100% on this...but I think the dude you target can already be a stud technically.

That would require a rules clarification though.

2021-04-04 13:46 UTC, tybar commented on server/game/cards/11-TCaR/FriendsInHighPlaces.js
> +        return playerPosseDudes.reduce((memo, dude) => memo + dude.influence, 0);
My ignorance showing, but what is "memo" in this context? Is that some sort of general memory of the game state?