Implemented Intercession and updated dude.js
townteki/townsquare pull request #713
Opened 2021-07-26 21:28 UTC by AaronSchnabel

added events for when a dude becomes a stud or draw

2021-07-28 21:29 UTC, mmeldo requested changes

2021-07-30 16:08 UTC, AaronSchnabel commented on server/game/dudecard.js
> +        this.game.raiseEvent('onDudeBecomesDraw', { card: this });
Removed.

2021-08-02 21:20 UTC, mmeldo requested changes

2021-08-02 21:20 UTC, mmeldo commented on server/game/cards/11-TCaR/Intercession.js
> +                cardCondition: card => card.controller === this.controller && card.location === 'play area',
Add prompt title.
```suggestion
            target: {
                activePromptTitle: 'Select your dude',
                waitingPromptTitle: 'Waiting for opponent to select a dude',
                cardCondition: card => card.controller === this.controller && card.location === 'play area',
```

2021-08-05 07:34 UTC, mmeldo approved these changes

2021-08-05 09:03 UTC, merged