Updated pronouns to neutral language
townteki/townsquare pull request #936
Opened 2021-09-09 22:40 UTC by AaronSchnabel

Also changed a number of other messages grammar to increase clarity.

2021-09-12 10:35 UTC, stopfstedt requested changes
LGTM overall, just a few grammatical errors that need to be addressed.

2021-09-12 11:00 UTC, mmeldo commented on server/game/cards/01-DTR/Bluetick.js
> +                this.game.addMessage('{0} uses {1} with it\'s master {2} to chase {3} in {4}.', context.player, this, this.parent, context.target, context.target.locationCard),
Also, we can use this PR to remove unnecessary dots in the game messages like here.

2021-09-12 11:03 UTC, stopfstedt commented on server/game/cards/01-DTR/Bluetick.js
> +                this.game.addMessage('{0} uses {1} with it\'s master {2} to chase {3} in {4}.', context.player, this, this.parent, context.target, context.target.locationCard),
good catch, suggested change updated :)

2021-09-14 13:32 UTC, mmeldo commented
How is this PR looking? Can we commit @stopfstedt suggestions and merge? They seems good to me.

2021-09-14 19:10 UTC, AaronSchnabel commented on server/game/cards/01-DTR/TravisMoone.js
> +                this.game.addMessage('{0} uses {1} to shuffle their hand to their draw deck and draw a new hand', context.player, this),
I made the change to "into" but left "draw" instead of draws, as the action is still referencing using Travis Moone.

2021-09-14 19:11 UTC, AaronSchnabel commented on server/game/dudecard.js
> +                waitingPromptTitle: 'Waiting for opponent to decide if they runs or fights'
I already updated this.

2021-09-14 19:12 UTC, AaronSchnabel commented
I'm committing most of them, going to change 

> 
> 
> How is this PR looking? Can we commit @stopfstedt suggestions and merge? They seems good to me.

I think it's ready to go now. I committed his changes with one small difference.

2021-09-14 19:41 UTC, mmeldo approved these changes
Looks good. Thanks.

2021-09-14 19:42 UTC, merged